version: '3.8'

services:
  web1:
    build:
      context: ./demo1/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./demo1/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env/dev.env
    networks:
      - app_network

  web2:
    build:
      context: ./demo2/
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./demo2/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
    ports:
      - "8080:8080"
    env_file:
      - ./.env/dev.env
    networks:
      - app_network

  nginx:
    build: 
      context: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles
    depends_on:
      - web1
      - web2
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  static_files:
