version: '3.9'

services:
  web:
    build:
      context: ./demo/
    image: nginx-web:04  # Name for the web service image
    command: gunicorn demo.wsgi:application --bind 0.0.0.0:8000  # Bind to all available network interfaces
    volumes:
      - ./demo/:/usr/src/app/
      - static_files:/usr/src/app/staticfiles
    expose:
      - 8000  # Expose internal port for communication with other containers
    env_file:
      - ./.env/dev.env

  nginx:
    build:
      context: ./nginx/
    image: nginx-nginx:04  # Name for the nginx service image
    ports:
      - "10.10.0.45:80:80"  # Bind Nginx to 10.10.0.45 on port 80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles
    # restart: always


volumes:
  static_files:


# docker-compose exec web python manage.py collectstatic --noinput



  # dns:
  #   build:
  #     context: ./dns/
  #   restart: always
  #   ports:
  #     - 53:53
  #     - 53:53/udp
  #   volumes:
  #     - ./dns/named.conf:/etc/bind/named.conf
  #     - ./dns/zone/:/etc/bind/zone/
  #   command: named -c /etc/bind/named.conf -g -u named