services:
  nginx:
    build:
      context: .  # Specify the build context
    image: custom-nginx-image  # Specify the image name you want
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    